local files = {
    {name = "RimurusMenu", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/RimurusMenu.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\" },
    {name = "Rimmuru\\libs\\GLTW", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/GLTW.lua", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Rimmuru\\libs\\Get Input", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/Get%20Input.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Rimmuru\\libs\\Functionslib", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/Functionslib.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Rimmuru\\libs\\moduleInstaller", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/moduleInstaller.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Rimmuru\\libs\\settings", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/settings.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Rimmuru\\libs\\feats\\playerOptions", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/playerOptions.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Rimmuru\\libs\\feats\\Aimbot", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/Aimbot.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Rimmuru\\libs\\feats\\Drone", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/Drone.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Rimmuru\\libs\\feats\\World", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/World.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Rimmuru\\libs\\feats\\editor", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/editor.luac" , path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
}
return files
