local files = {
    {name = "RimurusMenu.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/RimurusMenu.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\" },
    {name = "GLTW.lua", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/GLTW.lua", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Get Input.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/Get%20Input.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "Functionslib.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/Functionslib.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "moduleInstaller.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/moduleInstaller.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "settings.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/settings.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs" },
    {name = "playerOptions.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/playerOptions.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Aimbot.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/Aimbot.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "Drone.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/Drone.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "World.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/World.luac", path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
    {name = "editor.luac", link = "https://raw.githubusercontent.com/Rimmuru/Rimurus-2T1-Scripts/main/Rimurus%20Scripts/Rimurus%20Menu/Rimuru/libs/feats/editor.luac" , path = utils.get_appdata_path("PopstarDevs", "2Take1Menu").."\\".."scripts\\Rimuru\\libs\\feats" },
}
return files
