return {
	["welcome"] = [=[欢迎使用]=],
	["Self"] = [=[自我选项]=],
	["Weapon"] = [=[武器选项]=],
	["Vehicle"] = [=[载具选项]=],
	["Online"] = [=[线上选项]=],
	["Miscellanious"] = [=[其它选项]=],	
	["World"] = [=[世界选项]=],	
	["Script Repository"] = [=[脚本仓库]=],
	["Embed Scripts"] = [=[嵌入脚本]=],
	["Script Features"] = [=[脚本功能]=],
	["Settings"] = [=[设置选项]=],	
	
	["selfSub"] = {
		["visions"] = [=[视觉选项]=],
		["fov"] = [=[视野设置]=],
		["opacity"] = [=[人物可见程度]=],		
		["resetOpacity"] = [=[重置人物可见程度]=],
		["becomeCop"] = [=[警察模式]=],		
		["tinyPlayer"] = [=[缩小人物模型]=],
		["reduced"] = [=[减少碰撞效果]=],		
		["moneyDrops"] = [=[掉落钱袋 $2000]=],
		--VisionsSub
		["idle"] = [=[禁用闲置镜头]=],
		["nightvision"] = [=[夜视仪镜头]=],
		["heatvision"] = [=[热成像镜头]=],
		["clearAll"] = [=[清除所有效果]=],
	},
	
	["weaponSub"] = {
		["crosshair"] = [=[始终显示准星]=],
		["cartoon"] = [=[卡通枪]=],
		["dildo"] = [=[假阳具枪]=],
		["ped"] = [=[NPC 枪]=],		
		["object"] = [=[物品枪]=],
		["delete"] = [=[删除枪]=],
		["grapple"] = [=[钩爪枪]=],
		["dust"] = [=[尘土枪]=],
		["moneyGun"] = [=[钱袋枪]=],
		["teleportGun"] = [=[传送枪]=],	
		["rapidFire"] = [=[快速射击]=],
		["deadEye"] = [=[死神之眼]=],	
		["bulletTracer"] = [=[曳光子弹]=],		
		["damageMulti"] = [=[伤害调整]=],
		["meleeDamage"] = [=[近战伤害调整]=],
	},
	
	["vehicleSub"] = {
		["hexVehicle"] = [=[16进制颜色]=],
		["moddedColours"] = [=[精调颜色]=],
		["saveColour"] = [=[保存当前载具颜色]=],
		["vehGod"] = [=[载具无敌]=],		
		["vehOpacity"] = [=[载具不透明度]=],
		["vehGravity"] = [=[载具重力]=],
		["modifySpeed"] = [=[最大速度]=],
		["dirtLevel"] = [=[污垢程度]=],
		["destroy"] = [=[摧毁个人载具]=],
		["tpPersonal"] = [=[传送到个人载具]=],		
		["garage"] = [=[绕过车库检测]=],		
		["gtaNeon"] = [=[GTA4 霓虹灯]=],		
		["rgbNeon"] = [=[RGB 霓虹灯]=],		
		["rgbXenon"] = [=[RGB 大灯]=],		
		["exhaust"] = [=[排气效果]=],
		["noGrip"] = [=[漂移模式]=],
		["instantly"] = [=[瞬间进入/离开载具]=],
		["reduced"] = [=[减少载具碰撞效果]=],
		["speedo"] = [=[车速表]=],
	},
	
		["onlineSub"] = {
		["host"] = [=[主机选项]=],
		["mmanager"] = [=[金钱管理]=],
		["recovery"] = [=[恢复选项]=],
		["reactions"] = [=[检测响应]=],	
		["friends"] = [=[好友列表]=],
		["requests"] = [=[战局服务]=],	
	},
		["Online Players"] = [=[线上玩家]=],
		["All Players"] = [=[所有玩家]=],
		["Go Ghosted To Player"] = [=[断开玩家同步]=],
		["Spectate Player"] = [=[观看玩家]=],
		["Malicious"] = [=[恶意选项]=],		
		["Trolling"] = [=[恶搞选项]=],
		["Teleport"] = [=[传送选项]=],	
		["Invites"] = [=[邀请选项]=],
		["Miscellaneous"] = [=[其它选项]=],
		["Send SMS"] = [=[发送短信]=],
		
		["Go Ghosted To Lobby"] = [=[断开战局同步]=],
		
		--恶意选项
		["Explode Player"] = [=[爆炸玩家]=],
		["Kill Player"] = [=[杀死玩家]=],		
		["Sound Crash"] = [=[声音崩溃]=],		
		["Script Crash"] = [=[脚本崩溃]=],		
		["Vehicle Kick"] = [=[踢出载具]=],		
		["Force Into Data Breach"] = [=[强制发送到"数据泄露"]=],	
		["Force Into Severe Weather"] = [=[强制发送到"恶劣天气型态"]=],
		["Force Into Work Dispute"] = [=[强制发送到"工作纠纷"]=],
		["Force Into Cayo"] = [=[强制进入佩里科岛]=],
		["Force Into Cutscene"] = [=[强制进入剧情]=],		
		
		["Kick All"] = [=[踢出所有玩家]=],
		["Kick All Cheating"] = [=[踢出所有玩家 (因作弊...)]=],
		["Force Lobby Into Servere Weather"] = [=[强制发送所有人到"恶劣天气型态"]=],
		["Force Lobby Into Cutscene"] = [=[强制进入剧情]=],
		["Force Lobby To Cayo"] = [=[强制进入佩里科岛]=],
		["SE Lobby Kick"] = [=[脚本事件踢]=],
		["Crash"] = [=[崩溃所有玩家]=],
		
		--恶搞选项
		["Fake Money Bag Drop"] = [=[假钱袋掉落]=],
		["Fake Money Drop"] = [=[假钱掉落]=],
		["Cage"] = [=[笼子困住]=],
		["Fake Suspended"] = [=[虚假封号一个月]=],
		["Fake Ban"] = [=[虚假永久封号]=],
		["Kinetic Emp"] = [=[电磁脉冲感应地雷]=],
		["Water Jet"] = [=[水柱喷射]=],
		["Fire Jet"] = [=[火焰喷射]=],
		["Steam Jet"] = [=[蒸汽喷射]=],
		["Cash Removed "] = [=[虚假移除现金]=],			
		["Cash Stolen"] = [=[虚假窃取现金]=],
		["Cash Banked"] = [=[虚假现金存入银行]=],
		["Cash Dropped"] = [=[虚假现金掉落]=],

		["Destroy Lobbies Personal Vehicles"] = [=[摧毁所有玩家个人载具]=],
		["Fake Money Bag Drop Lobby"] = [=[假钱袋掉落]=],
		["Fake Money Drop Lobby"] = [=[假钱掉落]=],
		["Water Jet Lobby"] = [=[水柱喷射]=],
		["Fire Jet Lobby"] = [=[火焰喷射]=],
		["Steam Jet Lobby"] = [=[蒸汽喷射]=],
		["Cash Removed Lobby"] = [=[虚假移除现金]=],			
		["Cash Dropped Lobby"] = [=[虚假现金掉落]=],	
		["Cash Stolen Lobby"] = [=[虚假窃取现金]=],	
	
		--传送选项
		["Teleport To Player"] = [=[传送到玩家]=],
		["Teleport Peds To Player"] = [=[传送 NPC 到玩家]=],		
		["Teleport Vehicles To Player"] = [=[传送载具到玩家]=],
			
		--邀请选项
		["Penthouse Invite"] = [=[空中别墅邀请]=],
		["Apartment Invite"] = [=[公寓邀请]=],
		["Los Santos Customs Invite"] = [=[洛圣都改车王邀请]=],
		["Los Santos GolfClub Invite"] = [=[洛圣都高尔夫俱乐部邀请]=],
		["Hookies Invite"] = [=[胡奇酒吧邀请]=],
		["Pitchers Invite"] = [=[扎啤酒吧邀请]=],
		
		--其它选项
		["Drops"] = [=[掉落选项]=],
		["Give Bounty"] = [=[给予悬赏通缉]=],
		["Give Wanted"] = [=[给予通缉等级]=],
		["Trick Or Treat"] = [=[触发 "给糖或捣乱"]=],
		["Send Mugger"] = [=[发送劫匪窃取]=],
		["Copy player to spoof profile"] = [=[复制玩家信息作为伪装档案]=],
		["Copy SCID"] = [=[复制 R星ID]=],
		["Copy Name + SCID"] = [=[复制昵称 + R星ID]=],
		
		["Bounty"] = [=[悬赏通缉所有玩家]=],
		
		--掉落选项
		["Spawn Ped"] = [=[生成 Ped]=],
		["Rank up"] = [=[掉落收藏品]=],
		["RP Drop"] = [=[掉落纸牌]=],
		["Semi God"] = [=[给予半无敌]=],		
		
		--载具选项
		["Vehicle Godmode"] = [=[载具无敌]=],
		["Repair Vehicle"] = [=[修理载具]=],
		["Upgrade Vehicle"] = [=[升级载具]=],
		["Boost Vehicle"] = [=[加速载具]=],	
		["Destroy Personal Vehicle"] = [=[摧毁个人载具]=],

		["Boost Vehicles"] = [=[加速载具]=],	
		["Repair Vehicles"] = [=[修理载具]=],
		["Upgrade Vehicles"] = [=[升级载具]=],

		--主机选项
		["Session Size Limit"] = [=[战局最大人数限制]=],
		["Spectator Limit"] = [=[战局最大旁观人数限制]=],
		["Hide Session"] = [=[隐藏战局]=],
		["Block Migration"] = [=[禁止迁移脚本主机]=],

		--金钱管理
		["Transfer All Bank Cash To Wallet"] = [=[取出所有钱到钱包]=],
		["Transfer All Cash To Bank"] = [=[存入所有钱到银行]=],
		["Wallet Cash To Transfer"] = [=[存款到银行]=],
		["Trade Casino Chips"] = [=[置换筹码]=],
		["Acquire Casino Chips"] = [=[获取筹码]=],
		["Remove Money"] = [=[移除金钱]=],

		--恢复选项
		["Give Unlimited Snacks"] = [=[给予无限零食]=],
		["Give Unlimited Fireworks"] = [=[给予无限烟花]=],	
		["Unlock Xmas Gifts"] = [=[解锁圣诞节礼物]=],
		["Unlock Taxi Livery"] = [=[解锁出租车涂装]=],
		["Nightclub Loop"] = [=[夜总会循环]=],
		["Collectables"] = [=[收藏品]=],
		["Action Figures"] = [=[手办]=],
		["Organics"] = [=[拉玛有机坊产品]=],
		["Snowmen"] = [=[雪人]=],	

		--检测选项
		["Manual"] = [=[手动标记]=],
		["Player Model"] = [=[踢出触发"玩家模型"检测的玩家]=],
		["Scid Spoof"] = [=[踢出触发"伪装R星ID"检测的玩家]=],	
		["Invalid Ped"] = [=[踢出触发"无效人物模型"检测的玩家]=],
		["Model Change"] = [=[踢出触发"改变人物模型"检测的玩家]=],
		["Sync Crash"] = [=[踢出触发"同步崩溃"检测的玩家]=],
		["Net Crash"] = [=[踢出触发"网络崩溃"检测的玩家]=],
		["Host Token"] = [=[踢出触发"主机令牌过低"检测的玩家]=],
		["IP Spoof"] = [=[踢出触发"伪装IP"检测的玩家]=],
		["Karen"] = [=[踢出触发"Karen"检测的玩家]=],

		["Refresh"] = [=[刷新]=],
		
		--战局服务
		["Request heli pickup"] = [=[呼叫豪华直升机]=],	
		["Request boat pickup"] = [=[请求船只接送]=],
		["Request ammo drop"] = [=[空投弹药]=],
		["Request backup heli"] = [=[请求支援直升机]=],
		["Remove suicide cooldown"] = [=[移除自杀冷却]=],
		["Remove passive mode cooldown"] = [=[移除被动冷却]=],
		["Request Taxi"] = [=[呼叫出租车]=],
		["Request MOC"] = [=[呼叫机动作战中心]=],
		["Request Avenger"] = [=[呼叫复仇者]=],
		["Request Terrorbyte"] = [=[呼叫恐霸]=],
		["Request Acid Lab"] = [=[呼叫致幻剂实验室]=],
		["Request MiniTank"] = [=[启动 RC坦克]=],

		--其它选项
		["Riot Mode"] = [=[暴动模式]=],
		["Flash Mod"] = [=[闪电侠模式]=],	
		["Recon Drone"] = [=[侦察无人机]=],
		["Black Parade"] = [=[黑人游行抗议]=],
		["Respawn at death coords"] = [=[原地复活]=],	
		["No Target"] = [=[无目标 ?]=],
		["Crouch"] = [=[蹲下 ?]=],
		["Bail To Singleplayer"] = [=[返回故事模式]=],
		["Type As Rockstar"] = [=[发送带有认证图标的公屏信息]=],
		["Send Locked Chat Message"] = [=[发送带有锁图标的公屏信息]=],
		["Give Wings"] = [=[给予翅膀]=],
		["Remove Wings"] = [=[移除翅膀]=],
		["Hud Colours"] = [=[Hud 颜色]=],

		--世界选项,
		["Spawner"] = [=[生成选项]=],
		["worldSub"] = {
			["timeCycle"] = [=[滤镜修改]=],	
			["train"] = [=[火车选项]=],
			["esp"] = [=[透视选项]=],
			["party"] = [=[交通信号灯变色]=],
			
				["spawnerSub"] = {
					["namePed"] = [=[自定义生成 Ped]=],
					["peds"] = [=[NPC]=],			
					["animals"] = [=[动物]=],
					["spawned"] = [=[生成管理]=],								
				},
				["trainSub"] = {
					["Hijack"] = [=[窃取火车]=],
					["speed"] = [=[火车最大速度]=],
					["drive"] = [=[驾驶火车]=],
					["change"] = [=[改变轨道]=],
					["derail"] = [=[火车脱轨]=],					
					["delete"] = [=[删除火车]=],
					["deleteAll"] = [=[删除所有火车]=],
				},
	
				["espSub"] = {
					["player"] = [=[透视玩家]=],
					["entity"] = [=[透视实体]=],
				},
		},
					["Spawned Objects"] = [=[已生成物品]=],
					["Spawned Peds"] = [=[已生成Ped]=],
					
					["ESP Colour"] = [=[透视颜色]=],
					["ESP Snaplines"] = [=[透视线条]=],
					["ESP box"] = [=[透视方框]=],
		--设置选项
		["Save Settings"] = [=[保存设置]=],
		["Save UI"] = [=[保存主题]=],
		["Load UI"] = [=[加载主题]=],
		["Menu pos X"] = [=[菜单位置 X轴]=],
		["Menu pos Y"] = [=[菜单位置 Y轴]=],
		["Header"] = [=[主题头部]=],
		["Layout"] = [=[菜单布局]=],
		["Controls"] = [=[操作按键]=],
		["Player Info Window"] = [=[玩家信息框]=],
		["Background"] = [=[选项背景]=],
		["Footer"] = [=[菜单底栏]=],
		["Game States"] = [=[游戏状态]=],
		["Fonts"] = [=[菜单字体]=],
		["Hotkey notifications"] = [=[热键通知]=],
		["Colours"] = [=[菜单颜色]=],
		["Languages"] = [=[翻译文件]=],
		
		--菜单布局
			["Max features"] = [=[最大显示行数]=],
			["Menu width"] = [=[菜单宽度]=],
			["Feature dimensions X"] = [=[选项尺寸 X轴]=],
			["Feature dimensions Y"] = [=[选项尺寸 Y轴]=],
			["Feature spacing"] = [=[选项间距]=],
			["Text Size"] = [=[选项文本尺寸]=],
			["Footer Text Size"] = [=[底栏文本尺寸]=],
			["Hint Text Size"] = [=[注释文本尺寸]=],
			["Text Y Offset"] = [=[文本 上下偏移]=],
			["Border"] = [=[边框尺寸]=],
			["Selector Speed"] = [=[选项切换速度]=],
			["Online Players Sort:"] = [=[线上玩家排序:]=],
			["Padding"] = [=[缩进]=],
			["Slider"] = [=[滑块]=],
			
			--缩进
			["Name Padding"] = [=[选项缩进]=],			
			["Parent Padding"] = [=[选项箭头缩进]=],
			["Value Padding"] = [=[数值框缩进]=],
			["Slider Padding"] = [=[调整框缩进]=],
			
			--滑块
			["Slider Width"] = [=[滑块宽度]=],
			["Slider Height"] = [=[滑块高度]=],
			["Slider Height Active"] = [=[已启用滑块高度]=],

			--操作按键
			["Open"] = [=[呼出/隐藏菜单]=],
			["Up"] = [=[向上]=],
			["Back"] = [=[返回]=],
			["Select"] = [=[选择]=],
			["Down"] = [=[向下]=],
			["Right"] = [=[向右]=],
			["Special Key"] = [=[特殊功能键]=],
			["Set Hotkey"] = [=[设置热键]=],
			["Left"] = [=[向左]=],
			
			--玩家信息框
			["Draw"] = [=[绘制玩家信息框]=],
			["X Offset"] = [=[X轴 偏移]=],
			["Y Offset"] = [=[Y轴 偏移]=],
			["Spacing"] = [=[间隔]=],
			["Width"] = [=[宽度]=],
			
			--选项背景
			["Fit background to width"] = [=[使背景与宽度相适应]=],
			["Background pos X"] = [=[背景位置 X轴]=],
			["Background pos Y"] = [=[背景位置 Y轴]=],
			["Background Size"] = [=[背景尺寸]=],
			
			--菜单底栏
			["Footer Size"] = [=[底栏尺寸]=],
			["Footer Y Offset"] = [=[底栏上下偏移]=],
			["Draw footer"] = [=[绘制底栏]=],
			["Footer position based on background"] = [=[背景决定底栏位置]=],
			
			--游戏状态
			["Typing"] = [=[输入]=],	
			["Paused"] = [=[暂停选单]=],
			["CEO"] = [=[CEO]=],
			
			--菜单字体
			["Text Font"] = [=[文本字体]=],
			["Footer Font"] = [=[底栏字体]=],	
			["Hint Font"] = [=[注释字体]=],
			
			--热键通知
			["Toggle notification"] = [=[触发开关]=],
			["Action notification"] = [=[触发按钮]=],
			--菜单颜色
			["Pick Color"] = [=[色板取色]=],
			["Red"] = [=[红色]=],
			["Green"] = [=[绿色]=],
			["Blue"] = [=[蓝色]=],
			
			["Alpha"] = [=[透明度]=],
			["background"] = [=[选项背景]=],
			["border"] = [=[边框]=],
			["feature_bottomLeft"] = [=[选项左下角]=],
			["feature_bottomRight"] = [=[选项右下角]=],
			["feature_topLeft"] = [=[选项左上角]=],
			["feature_topRight"] = [=[选项右上角]=],
			["feature_selected_bottomLeft"] = [=[已选中选项左下角]=],
			["feature_selected_bottomRight"] = [=[已选中选项右下角]=],
			["feature_selected_topLeft"] = [=[已选中选项左上角]=],
			["feature_selected_topRight"] = [=[已选中选项右上角]=],
			["footer"] = [=[底栏]=],
			["footer_text"] = [=[底栏文本]=],
			["notifications"] = [=[通知栏]=],
			["side_window_background"] = [=[侧边窗口背景]=],
			["side_window_text"] = [=[侧边窗口文本]=],
			["slider_active"] = [=[已启用滑块按钮]=],
			["slider_background"] = [=[未选中滑块调整框]=],
			["slider_selectedActive"] = [=[已选中已启用滑块按钮]=],
			["slider_selectedBackground"] = [=[已选中滑块调整框]=],
			["slider_text"] = [=[滑块调整框文本]=],
			["sprite"] = [=[图片]=],
			["text"] = [=[文本]=],
			["text_selected"] = [=[已选中文本]=],
}