return {
	["fontID"] = 9,
	["feature_offset"] = 0.027083333333333,
	["states"] = {
		["embedScripts"] = true,
		["dildo"] = false,
		["grapple"] = false,
		["tiny"] = false,
		["paused"] = false,
		["idle"] = true,
		["teleport"] = false,
		["moneyGun"] = false,
		["night"] = false,
		["playerAimbot"] = false,
		["controllerSupport"] = false,
		["delete"] = false,
		["reduced"] = false,
		["heat"] = false,
		["object"] = false,
		["REQUEST_PICKUP_EVENT"] = false,
		["pedAimbot"] = false,
		["ALTER_WANTED_LEVEL_EVENT"] = false,
		["cartoon"] = false,
		["rapidFire"] = false,
		["crosshair"] = false,
		["REPORT_MYSELF"] = false,
		["dust"] = false,
		["paint"] = false,
		["KICK_VOTES_EVENT"] = false,
		["typing"] = true,
		["vip"] = false,
		["cop"] = false,
		["ped"] = false,
		["money"] = false,
	},
	["y"] = 0.328,
	["x"] = 0.172,
	["text_y_offset"] = -0.0055555555,
	["featColour"] = {
		["g"] = 0,
		["r"] = 0,
		["a"] = 0,
		["b"] = 0,
	},
	["mainColour"] = {
		["g"] = 0,
		["r"] = 36,
		["a"] = 255,
		["b"] = 69,
	},
	["padding"] = 0.003125,
	["width"] = 0.2,
	["footer"] = {
		["draw_footer"] = true,
		["footer_y_offset"] = 0,
		["footer_pos_related_to_background"] = true,
		["padding"] = 0.0078125,
		["footer_size"] = 0.019444444,
	},
	["backColour"] = {
		["g"] = 0,
		["r"] = 0,
		["a"] = 255,
		["b"] = 0,
	},
	["border"] = 0.0018518518518519,
	["header"] = [=[cute.png]=],
	["gradRightColour"] = {
		["g"] = 28,
		["r"] = 27,
		["a"] = 255,
		["b"] = 118,
	},
	["colorText"] = {
		["g"] = 255,
		["r"] = 255,
		["a"] = 200,
		["b"] = 255,
	},
	["maxOptions"] = 7,
	["font"] = [=[Neufreit.spritefont]=],
	["feature_scale"] = {
		["y"] = 0.025,
		["x"] = 0.2,
	},
	["height"] = 0.18958333333333,
	["textSize"] = 1.2,
	["side_window"] = {
		["on"] = true,
		["width"] = 0.3,
		["offset"] = {
			["y"] = 0,
			["x"] = 0.0,
		},
		["spacing"] = 0.0547222,
		["padding"] = 0.01,
	},
}